# HUD V2 — two floating islands at the top of the screen.
#   Left  island: day / weekday / time + current location.   (whole island clickable)
#   Right island: Cash | Energy | Hunger | State.            (each segment clickable)
# The centre of the screen stays empty by design.
#
# Everything visual lives in the HUD2 dict below — no raw hex anywhere else.
# Panel/bar shapes are white alpha masks generated by tools/gen_hud2_panels.py
# and tinted at runtime, so changing a colour here is the only edit needed.
#
# This file owns no gameplay state. `screen hud()` in hud.rpy uses `hud_v2`.

init -5 python:

    HUD2 = {
        # Panel appearance
        "bg":             "#1a1c1ecc",
        "bg_hover":       "#2a2e33cc",
        "border":         "#ffffff18",
        "radius":         18,

        # Typography
        "font":           "fonts/Quicksand-SemiBold.ttf",
        "text_primary":   "#f0ece4",
        "text_secondary": "#8a9298",

        # Semantic accents
        "money_color":    "#7abf7a",
        "energy_color":   "#5bcafa",
        "hunger_color":   "#c9a06a",
        "hygiene_color":  "#5abcaa",   # teal — no dedicated icon, shares wellbeing PNG
        "state_color":    "#a890d0",
        "warn_color":     "#e08a5a",

        # Bars
        "bar_track":      "#ffffff1a",
        "bar_w_compact":  118,
        "bar_h_compact":  5,
        "bar_w_expanded": 290,
        "bar_h_expanded": 8,

        # Divider
        "divider":        "#ffffff18",

        # Island geometry (1920x1080)
        "left_x":         28,
        "top_y":          22,
        "island_h":       92,
        "left_w":         390,
        "right_w":        780,   # 5 segments × 136 + 4 dividers + 8 × 8px gaps + 2 × 14px pad = 776; 780 gives 4px slack
        "right_margin":   28,
        "pad_x":          14,
        "pad_y":          9,
        "seg_w":          136,   # narrowed from 153 to fit 5 segments
        "seg_gap":        8,      # gap either side of each 1px divider
        "panel_y":        124,    # top edge of every expanded panel
        "panel_w":        340,
        "panel_w_wide":   360,
    }

    # Derived geometry — computed once at init, never per frame.
    HUD2["right_x"]  = 1920 - HUD2["right_margin"] - HUD2["right_w"]
    HUD2["seg_x0"]   = HUD2["right_x"] + HUD2["pad_x"]
    HUD2["seg_step"] = HUD2["seg_w"] + 2 * HUD2["seg_gap"] + 1
    HUD2["seg_h"]    = HUD2["island_h"] - 2 * HUD2["pad_y"]

    def hud2_panel_x(seg_index, w):
        """Left edge of the expanded panel under segment N, clamped to the screen."""
        return min(HUD2["seg_x0"] + seg_index * HUD2["seg_step"],
                   1920 - HUD2["right_margin"] - w)

    # ── Shape tinting ─────────────────────────────────────────────────────────
    # White alpha-mask PNGs recoloured through im.MatrixColor, so a single hex
    # string (with its alpha byte) drives both colour and opacity.
    def hud2_tint(path, hexcolor):
        r, g, b, a = Color(hexcolor).rgba
        return im.MatrixColor(path, im.matrix.tint(r, g, b) * im.matrix.opacity(a))

    def hud2_fill(hexcolor=None):
        return Frame(hud2_tint("images/ui/hud2/panel_r18.png", hexcolor or HUD2["bg"]),
                     HUD2["radius"], HUD2["radius"])

    def hud2_line(hexcolor=None):
        return Frame(hud2_tint("images/ui/hud2/panel_r18_line.png", hexcolor or HUD2["border"]),
                     HUD2["radius"], HUD2["radius"])

    def hud2_barpart(hexcolor, big=False):
        img = "images/ui/hud2/bar8.png" if big else "images/ui/hud2/bar5.png"
        return Frame(hud2_tint(img, hexcolor), 10, 0)

    # Built once — the compact HUD renders every frame, so it must not construct
    # displayables in screen expressions.
    HUD2_BG       = hud2_fill()
    HUD2_BG_HOVER = hud2_fill(HUD2["bg_hover"])
    HUD2_LINE     = hud2_line()
    HUD2_DIV      = Solid(HUD2["divider"])

    # ── Icon registry ─────────────────────────────────────────────────────────
    HUD2_ICONS = {
        "money":      "images/ui/hud_icons/01_money.png",
        "energy":     "images/ui/hud_icons/02_energy.png",
        "hunger":     "images/ui/hud_icons/03_hunger.png",
        "wellbeing":  "images/ui/hud_icons/04_wellbeing.png",
        # No dedicated hygiene icon in the asset set. Reusing 04_wellbeing.png under
        # a separate key so the State segment keeps its "wellbeing" fallback distinct.
        "hygiene":    "images/ui/hud_icons/04_wellbeing.png",
        "calendar":   "images/ui/hud_icons/05_day_calendar.png",
        "clock":      "images/ui/hud_icons/06_time_clock.png",
        "location":   "images/ui/hud_icons/07_location.png",
        "map":        "images/ui/hud_icons/08_map.png",
        "focused":    "images/ui/hud_icons/09_focused.png",
        "inspired":   "images/ui/hud_icons/10_inspired.png",
        "confident":  "images/ui/hud_icons/11_confident.png",
        "stressed":   "images/ui/hud_icons/12_stressed.png",
        "lonely":     "images/ui/hud_icons/13_lonely.png",
        "reputation": "images/ui/hud_icons/14_reputation.png",
        "followers":  "images/ui/hud_icons/15_followers.png",
        "expand":     "images/ui/hud_icons/16_expand_details.png",
    }

    # Pre-sized icon displayables — screens never build a path or Transform.
    HUD2_ICON = {}
    for _hk, _hp in HUD2_ICONS.items():
        for _hs in (20, 22, 26):
            HUD2_ICON[(_hk, _hs)] = Transform(_hp, size=(_hs, _hs))

    def hud2_state_icon(state_id):
        """Icon path for a player state; falls back to the wellbeing icon."""
        return HUD2_ICONS.get(state_id, HUD2_ICONS["wellbeing"])

    def hud2_icon(key, size=20):
        return HUD2_ICON.get((key, size)) or HUD2_ICON[("wellbeing", size)]

    # ── Player-state helpers (read player_states / PLAYER_STATE_DEFS only) ─────
    def hud2_active_states():
        """Active player states as display dicts, in PLAYER_STATE_DEFS priority order.
        Cheap by construction: player_states is capped at 2 entries."""
        order = list(PLAYER_STATE_DEFS.keys())
        live = [s for s in store.player_states if s.get("expires_day", 0) > store.day]
        live.sort(key=lambda s: order.index(s["state_id"]) if s["state_id"] in order else 99)
        out = []
        for s in live:
            d = PLAYER_STATE_DEFS.get(s["state_id"], {})
            out.append({
                "id":        s["state_id"],
                "title":     d.get("title", s["state_id"]),
                "desc":      d.get("desc", ""),
                "days_left": max(0, s.get("expires_day", store.day) - store.day),
                "icon":      hud2_state_icon(s["state_id"]),
            })
        return out

    def hud2_primary_state():
        st = hud2_active_states()
        return st[0] if st else None

    def hud2_state_label():
        st = hud2_active_states()
        if not st:
            return "No effects"
        if len(st) == 1:
            return st[0]["title"]
        return "%s +%d" % (st[0]["title"], len(st) - 1)

    # ── Location helpers ──────────────────────────────────────────────────────
    def hud2_location_label():
        """Human-readable name of the current location."""
        loc = store.current_loc or ""
        name = LOCATION_NAMES.get(loc)
        if not name:
            name = loc.replace("location_", "").replace("_", " ").title()
        elif name[:4].lower() == "the ":
            name = name[4:]
        return (name[:1].upper() + name[1:]) if name else "Somewhere"

    def hud2_people_here():
        """Display names of NPCs interactable at the current location.
        Wraps the living-world visibility helper; iterates every NPC, so it is
        only called when the expanded left panel is opened — never per frame."""
        # Phase 66: the stage LABEL only — never the four raw axes. Those live
        # in the Contacts app; People Here stays a glance, not a dashboard.
        out = []
        for n in public_talkable_npcs_here():
            if not npc_has_been_encountered(n):
                out.append("Stranger")
                continue
            out.append("%s  ·  %s" % (NPC_DATA[n]["name"],
                                      npc_relationship_stage_label(n)))
        return out

    # ── Need read-outs. Labels/effects derive from the canonical gameplay
    #    thresholds in data.rpy: too_tired() energy < 20, worn_out() energy < 30
    #    or hunger < 25, eff_app() hygiene tiers 60/40/20.
    def hud2_energy_status():
        e = store.need_energy
        if e < 20: return ("Exhausted", HUD2["warn_color"])
        if e < 30: return ("Worn out", HUD2["warn_color"])
        return ("Rested", HUD2["energy_color"])

    def hud2_energy_effect():
        e = store.need_energy
        if e < 20: return "Below 20: demanding activities are blocked."
        if e < 30: return "Below 30: work and performance quality suffer."
        return "No penalties right now."

    def hud2_hunger_status():
        h = store.need_hunger
        if h < 25: return ("Starving", HUD2["warn_color"])
        if h < 50: return ("Peckish", HUD2["hunger_color"])
        return ("Fed", HUD2["hunger_color"])

    def hud2_hunger_effect():
        if store.need_hunger < 25:
            return "Below 25: work and performance quality suffer."
        return "No penalties right now."

    def hud2_hygiene_status():
        # Thresholds from eff_app() in data.rpy: 60/40/20 → −0/5/12/22 Appearance.
        h = store.need_hygiene
        if h >= 60: return ("Clean",   HUD2["hygiene_color"])
        if h >= 40: return ("Unkempt", HUD2["warn_color"])
        if h >= 20: return ("Grubby",  HUD2["warn_color"])
        return ("Filthy", HUD2["warn_color"])

    def hud2_hygiene_effect():
        h = store.need_hygiene
        if h >= 60: return "No Appearance penalty."
        if h >= 40: return "Below 60: Appearance −5."
        if h >= 20: return "Below 40: Appearance −12."
        return "Below 20: Appearance −22."

    def hud2_hygiene_note():
        """Appearance penalty summary — kept for backward compat (test_hud_v2, energy panel legacy)."""
        h = store.need_hygiene
        debuff = 0 if h >= 60 else (5 if h >= 40 else (12 if h >= 20 else 22))
        if not debuff:
            return "Hygiene %d — no Appearance penalty." % h
        return "Hygiene %d — Appearance -%d." % (h, debuff)

    def hud2_money_str(value):
        return "$" + format(int(value), ",")

    def hud2_today_money():
        """(earned, spent) so far today, from the canonical activity log."""
        log = store.current_day_activity
        earned = sum(e["metadata"].get("amount", 0) for e in log
                     if e["category"] == "money" and e["metadata"].get("amount", 0) > 0)
        spent = abs(sum(e["metadata"].get("amount", 0) for e in log
                        if e["category"] == "money" and e["metadata"].get("amount", 0) < 0))
        return earned, spent

    def hud2_stock_value():
        # ponytail: stock_price can lag stock_owned on an old save — swallow rather
        # than crash the HUD. Upgrade path: have stocks_init() backfill missing keys.
        try:
            return portfolio_value() if store.stock_owned else 0
        except Exception:
            return 0

    def set_hud(mode):
        """Switch the HUD island visibility.
        Call from labels: $ set_hud("hidden") before a CG, $ set_hud("full") after.
        Values: "full" (default) | "minimal" (left island only) | "hidden" (nothing).

        NOTE: This infrastructure is ready but CG suppression has not yet been wired
        into specific scene labels — that is a follow-up pass. Do not add set_hud()
        calls to scenes in this task; only the mechanism is being built here.
        """
        store.hud_mode = mode
        renpy.restart_interaction()
        return None


# UI-only: which expanded panel is open. None | left | cash | energy | hunger | state | hygiene
default _hud2_expanded = None


# ══════════════════════════════════════════════════════════════════════════════
# BAR STYLES — rounded caps, no thumb, no scrollbar behaviour.
# ══════════════════════════════════════════════════════════════════════════════

style hud2_bar is bar:
    thumb Null()
    thumb_shadow Null()
    thumb_offset 0
    bar_vertical False
    xsize HUD2["bar_w_compact"]
    ysize HUD2["bar_h_compact"]
    right_bar hud2_barpart(HUD2["bar_track"])

style hud2_bar_energy is hud2_bar:
    left_bar hud2_barpart(HUD2["energy_color"])

style hud2_bar_hunger is hud2_bar:
    left_bar hud2_barpart(HUD2["hunger_color"])

style hud2_bar_big is hud2_bar:
    xsize HUD2["bar_w_expanded"]
    ysize HUD2["bar_h_expanded"]
    right_bar hud2_barpart(HUD2["bar_track"], True)

style hud2_bar_energy_big is hud2_bar_big:
    left_bar hud2_barpart(HUD2["energy_color"], True)

style hud2_bar_hunger_big is hud2_bar_big:
    left_bar hud2_barpart(HUD2["hunger_color"], True)

style hud2_bar_hygiene is hud2_bar:
    left_bar hud2_barpart(HUD2["hygiene_color"])

style hud2_bar_hygiene_big is hud2_bar_big:
    left_bar hud2_barpart(HUD2["hygiene_color"], True)


# ══════════════════════════════════════════════════════════════════════════════
# SHELL — rounded translucent panel + hairline border. Two nested frames,
# because a Ren'Py frame accepts only one background displayable.
# ══════════════════════════════════════════════════════════════════════════════

screen hud2_shell(w, pad_x=16, pad_y=14):
    frame:
        background HUD2_BG
        xsize w
        padding (0, 0, 0, 0)
        frame:
            background HUD2_LINE
            xfill True
            padding (pad_x, pad_y, pad_x, pad_y)
            transclude


# ══════════════════════════════════════════════════════════════════════════════
# COMPACT HUD
# ══════════════════════════════════════════════════════════════════════════════

screen hud_v2():

    $ _h2_day   = "DAY %d · %s" % (day + 1, day_name(day)[:3].upper())
    $ _h2_time  = time_label(hour)
    $ _h2_loc   = hud2_location_label()
    $ _h2_state = hud2_primary_state()

    # ── LEFT ISLAND ───────────────────────────────────────────────────────────
    button:
        xpos HUD2["left_x"]
        ypos HUD2["top_y"]
        xysize (HUD2["left_w"], HUD2["island_h"])
        padding (0, 0, 0, 0)
        background HUD2_BG
        hover_background HUD2_BG_HOVER
        action SetVariable("_hud2_expanded", None if _hud2_expanded == "left" else "left")
        tooltip "Day, time, location - and who is here."
        frame:
            background HUD2_LINE
            xfill True
            yfill True
            padding (HUD2["pad_x"], HUD2["pad_y"], HUD2["pad_x"], HUD2["pad_y"])
            vbox:
                spacing 5
                # fixed, not hbox: xalign only pushes a child to the right edge
                # inside a container that gives it the full width.
                fixed:
                    xysize (HUD2["left_w"] - 2 * HUD2["pad_x"], 28)
                    text _h2_day:
                        font HUD2["font"] size 15 color HUD2["text_secondary"]
                        xalign 0.0 yalign 1.0
                    text _h2_time:
                        font HUD2["font"] size 22 color HUD2["text_primary"]
                        xalign 1.0 yalign 0.5
                add HUD2_DIV xysize (HUD2["left_w"] - 2 * HUD2["pad_x"], 1)
                hbox:
                    spacing 8
                    add hud2_icon("location", 22) yalign 0.5
                    text _h2_loc:
                        font HUD2["font"] size 17 color HUD2["text_primary"] yalign 0.5

    # ── RIGHT ISLAND ──────────────────────────────────────────────────────────
    frame:
        xpos HUD2["right_x"]
        ypos HUD2["top_y"]
        xysize (HUD2["right_w"], HUD2["island_h"])
        background HUD2_BG
        padding (0, 0, 0, 0)
        frame:
            background HUD2_LINE
            xfill True
            yfill True
            padding (HUD2["pad_x"], HUD2["pad_y"], HUD2["pad_x"], HUD2["pad_y"])
            hbox:
                spacing HUD2["seg_gap"]

                use hud2_segment("cash", "money", "CASH", hud2_money_str(money),
                                 HUD2["money_color"], None, None,
                                 "Cash on hand.")
                add HUD2_DIV xysize (1, HUD2["seg_h"])
                use hud2_segment("energy", "energy", "ENERGY", str(int(need_energy)),
                                 HUD2["energy_color"], need_energy, "hud2_bar_energy",
                                 "Energy - sleep to refill. Below 20 blocks demanding activities.")
                add HUD2_DIV xysize (1, HUD2["seg_h"])
                use hud2_segment("hunger", "hunger", "HUNGER", str(int(need_hunger)),
                                 HUD2["hunger_color"], need_hunger, "hud2_bar_hunger",
                                 "Hunger - eat at home or order from your phone.")
                add HUD2_DIV xysize (1, HUD2["seg_h"])
                use hud2_segment("hygiene", "hygiene", "HYGIENE", str(int(need_hygiene)),
                                 HUD2["hygiene_color"], need_hygiene, "hud2_bar_hygiene",
                                 "Hygiene - shower at home to refill. Below 60 reduces Appearance.")
                add HUD2_DIV xysize (1, HUD2["seg_h"])
                use hud2_segment("state", (_h2_state["id"] if _h2_state else "wellbeing"),
                                 "STATE", hud2_state_label(),
                                 HUD2["state_color"], None, None,
                                 "Temporary states affecting you.")

    # ── EXPANDED PANELS (one at a time) ───────────────────────────────────────
    if _hud2_expanded == "left":
        vbox:
            xpos HUD2["left_x"]
            ypos HUD2["panel_y"]
            use hud2_panel_left
    elif _hud2_expanded == "cash":
        vbox:
            xpos hud2_panel_x(0, HUD2["panel_w"])
            ypos HUD2["panel_y"]
            use hud2_panel_cash
    elif _hud2_expanded == "energy":
        vbox:
            xpos hud2_panel_x(1, HUD2["panel_w"])
            ypos HUD2["panel_y"]
            use hud2_panel_need("energy")
    elif _hud2_expanded == "hunger":
        vbox:
            xpos hud2_panel_x(2, HUD2["panel_w"])
            ypos HUD2["panel_y"]
            use hud2_panel_need("hunger")
    elif _hud2_expanded == "hygiene":
        vbox:
            xpos hud2_panel_x(3, HUD2["panel_w"])
            ypos HUD2["panel_y"]
            use hud2_panel_hygiene
    elif _hud2_expanded == "state":
        vbox:
            xpos hud2_panel_x(4, HUD2["panel_w_wide"])
            ypos HUD2["panel_y"]
            use hud2_panel_state


screen hud2_segment(seg_id, icon_key, cap, value, accent, bar_value, bar_style, tip):
    button:
        xysize (HUD2["seg_w"], HUD2["seg_h"])
        padding (0, 0, 0, 0)
        background None
        hover_background HUD2_BG_HOVER
        action SetVariable("_hud2_expanded", None if _hud2_expanded == seg_id else seg_id)
        tooltip tip
        vbox:
            spacing 2
            xalign 0.5
            yalign 0.5
            add hud2_icon(icon_key, 20) xalign 0.5
            text cap:
                font HUD2["font"] size 11 color HUD2["text_secondary"] xalign 0.5
            text value:
                font HUD2["font"] size 19 color accent xalign 0.5
            if bar_value is not None:
                bar:
                    value StaticValue(bar_value, 100)
                    style bar_style
                    xalign 0.5


# ══════════════════════════════════════════════════════════════════════════════
# EXPANDED PANELS
# ══════════════════════════════════════════════════════════════════════════════

screen hud2_panel_left():
    # people_here_dock (activity_menu.rpy) is suppressed while this panel is open.
    $ _h2_people = hud2_people_here()      # heavy: only runs on open, not per frame
    use hud2_shell(HUD2["panel_w_wide"]):
        vbox:
            spacing 9
            hbox:
                spacing 8
                add hud2_icon("calendar", 22) yalign 0.5
                text ("Day %d · %s" % (day + 1, day_name(day))):
                    font HUD2["font"] size 18 color HUD2["text_primary"] yalign 0.5
            hbox:
                spacing 8
                add hud2_icon("clock", 22) yalign 0.5
                text time_label(hour):
                    font HUD2["font"] size 18 color HUD2["text_primary"] yalign 0.5
            hbox:
                spacing 8
                add hud2_icon("location", 22) yalign 0.5
                text hud2_location_label():
                    font HUD2["font"] size 18 color HUD2["text_primary"] yalign 0.5
            add HUD2_DIV xysize (HUD2["panel_w_wide"] - 32, 1)
            text "PEOPLE HERE":
                font HUD2["font"] size 11 color HUD2["text_secondary"]
            if _h2_people:
                for _h2_nm in _h2_people:
                    text ("· " + _h2_nm):
                        font HUD2["font"] size 16 color HUD2["text_primary"]
            else:
                text "Nobody around right now.":
                    font HUD2["font"] size 15 color HUD2["text_secondary"]


screen hud2_panel_cash():
    $ _h2_earned, _h2_spent = hud2_today_money()
    $ _h2_stocks = hud2_stock_value()
    $ _h2_kvw = HUD2["panel_w"] - 32          # panel width minus hud2_shell padding
    use hud2_shell(HUD2["panel_w"]):
        vbox:
            spacing 8
            hbox:
                spacing 8
                add hud2_icon("money", 26) yalign 0.5
                text hud2_money_str(money):
                    font HUD2["font"] size 26 color HUD2["money_color"] yalign 0.5
            add HUD2_DIV xysize (HUD2["panel_w"] - 32, 1)
            use hud2_kv("Earned today", "+" + hud2_money_str(_h2_earned), HUD2["money_color"], _h2_kvw)
            use hud2_kv("Spent today", "-" + hud2_money_str(_h2_spent), HUD2["text_primary"], _h2_kvw)
            if _h2_stocks:
                use hud2_kv("Stock holdings", hud2_money_str(_h2_stocks), HUD2["money_color"], _h2_kvw)
            if loan:
                use hud2_kv("Outstanding loan", hud2_money_str(loan), HUD2["warn_color"], _h2_kvw)


screen hud2_kv(cap, value, accent, w):
    fixed:
        xysize (w, 22)
        text cap:
            font HUD2["font"] size 14 color HUD2["text_secondary"]
            xalign 0.0 yalign 0.5
        text value:
            font HUD2["font"] size 16 color accent
            xalign 1.0 yalign 0.5


screen hud2_panel_need(which):
    $ _h2_e   = (which == "energy")
    $ _h2_val = need_energy if _h2_e else need_hunger
    $ _h2_status, _h2_col = hud2_energy_status() if _h2_e else hud2_hunger_status()
    $ _h2_eff = hud2_energy_effect() if _h2_e else hud2_hunger_effect()
    use hud2_shell(HUD2["panel_w"]):
        vbox:
            spacing 9
            fixed:
                xysize (HUD2["panel_w"] - 32, 32)
                hbox:
                    spacing 8
                    xalign 0.0 yalign 0.5
                    add hud2_icon("energy" if _h2_e else "hunger", 26) yalign 0.5
                    text ("%d / 100" % int(_h2_val)):
                        font HUD2["font"] size 24 yalign 0.5
                        color (HUD2["energy_color"] if _h2_e else HUD2["hunger_color"])
                text _h2_status:
                    font HUD2["font"] size 15 color _h2_col
                    xalign 1.0 yalign 0.5
            bar:
                value StaticValue(_h2_val, 100)
                style ("hud2_bar_energy_big" if _h2_e else "hud2_bar_hunger_big")
            add HUD2_DIV xysize (HUD2["panel_w"] - 32, 1)
            text _h2_eff:
                font HUD2["font"] size 14 color HUD2["text_secondary"]


screen hud2_panel_state():
    $ _h2_states = hud2_active_states()
    use hud2_shell(HUD2["panel_w_wide"]):
        vbox:
            spacing 10
            text "ACTIVE STATES":
                font HUD2["font"] size 11 color HUD2["text_secondary"]
            if _h2_states:
                for _h2_st in _h2_states:
                    hbox:
                        spacing 10
                        add Transform(_h2_st["icon"], size=(26, 26))
                        vbox:
                            spacing 2
                            hbox:
                                spacing 8
                                text _h2_st["title"]:
                                    font HUD2["font"] size 17 color HUD2["state_color"]
                                text ("%dd left" % _h2_st["days_left"]):
                                    font HUD2["font"] size 13 color HUD2["text_secondary"] yalign 1.0
                            text _h2_st["desc"]:
                                font HUD2["font"] size 14 color HUD2["text_secondary"]
                                xsize HUD2["panel_w_wide"] - 70
            else:
                text "Nothing affecting you right now.":
                    font HUD2["font"] size 15 color HUD2["text_secondary"]


screen hud2_panel_hygiene():
    # Thresholds from eff_app() in data.rpy: need_hygiene 60/40/20 → Appearance −0/5/12/22.
    $ _h2_val = need_hygiene
    $ _h2_status, _h2_col = hud2_hygiene_status()
    $ _h2_eff = hud2_hygiene_effect()
    use hud2_shell(HUD2["panel_w"]):
        vbox:
            spacing 9
            fixed:
                xysize (HUD2["panel_w"] - 32, 32)
                hbox:
                    spacing 8
                    xalign 0.0 yalign 0.5
                    add hud2_icon("hygiene", 26) yalign 0.5
                    text ("%d / 100" % int(_h2_val)):
                        font HUD2["font"] size 24 yalign 0.5
                        color HUD2["hygiene_color"]
                text _h2_status:
                    font HUD2["font"] size 15 color _h2_col
                    xalign 1.0 yalign 0.5
            bar:
                value StaticValue(_h2_val, 100)
                style "hud2_bar_hygiene_big"
            add HUD2_DIV xysize (HUD2["panel_w"] - 32, 1)
            text _h2_eff:
                font HUD2["font"] size 14 color HUD2["text_secondary"]
            text "Shower at home to restore hygiene.":
                font HUD2["font"] size 14 color HUD2["text_secondary"]


# ══════════════════════════════════════════════════════════════════════════════
# MINIMAL HUD — left island only (day/time/location), no resource HUD.
# Used for cutscenes where the player needs spatial context but full
# resource chrome would be distracting. Switch via: $ set_hud("minimal")
#
# CG suppression (set_hud("hidden")) is infrastructure-ready here but not yet
# wired into specific scene labels — that will be done in a follow-up pass.
# ══════════════════════════════════════════════════════════════════════════════

screen hud_v2_minimal():
    $ _h2_day  = "DAY %d · %s" % (day + 1, day_name(day)[:3].upper())
    $ _h2_time = time_label(hour)
    $ _h2_loc  = hud2_location_label()

    button:
        xpos HUD2["left_x"]
        ypos HUD2["top_y"]
        xysize (HUD2["left_w"], HUD2["island_h"])
        padding (0, 0, 0, 0)
        background HUD2_BG
        hover_background HUD2_BG_HOVER
        action NullAction()
        frame:
            background HUD2_LINE
            xfill True
            yfill True
            padding (HUD2["pad_x"], HUD2["pad_y"], HUD2["pad_x"], HUD2["pad_y"])
            vbox:
                spacing 5
                fixed:
                    xysize (HUD2["left_w"] - 2 * HUD2["pad_x"], 28)
                    text _h2_day:
                        font HUD2["font"] size 15 color HUD2["text_secondary"]
                        xalign 0.0 yalign 1.0
                    text _h2_time:
                        font HUD2["font"] size 22 color HUD2["text_primary"]
                        xalign 1.0 yalign 0.5
                add HUD2_DIV xysize (HUD2["left_w"] - 2 * HUD2["pad_x"], 1)
                hbox:
                    spacing 8
                    add hud2_icon("location", 22) yalign 0.5
                    text _h2_loc:
                        font HUD2["font"] size 17 color HUD2["text_primary"] yalign 0.5
